language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r httr testthat knitr"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
- "./travis-tool.sh github_package jimhester/covr"
notifications:
  email:
    on_success: change
    on_failure: change
script: "./travis-tool.sh run_tests"
after_failure:
  - "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: FvJg5DQJykXEyqa2fb4NCYFK1l/c5V3DnUQ40lkMtUIS0auyplDGhNiRdPqGKlGpZRLbjpgcquNDtqKtqvm41AKrIOBRXufl/Gu9weLjbo8WyvzXvfrEzR4oIOI0MdanIML5B9Ps72UJPn0SJoCVlCV/bwNSK6TXoF8vCDUM9gI=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
