language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r httr testthat knitr"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: YR8MyHWv8gRhZGo5eDItM6dNCG4yQFtVjpa/5Q/ybMNgZf2OG8mCdiyg4CQGPuaGVR5OP2SnJVo3bX1FFfymjYfQhyUdpb8Lou9CHACMyRrX6oFWhmMtvM9AflpNN+6Rf5XJXYMlK+ZyRnu68JOsRLnarb6zDzihnR2SgTn7+8E=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
